services:
  thermoscan-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: thermoscan_cad_app
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./interface:/app/interface
      - ./api:/app/api
      - ./treinamento:/app/treinamento
