services:
  deepvision-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: deepvision_cade_app

    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./interface:/app/interface
      - ./api:/app/api
      - ./treinamento:/app/treinamento
